// <auto-generated />
using System;
using Atraccion.Microservicios.Factura.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atraccion.Microservicios.Factura.DataAccess.Migrations
{
    [DbContext(typeof(AtraccionesDbContext))]
    [Migration("20260513215231_FacturaModificationA")]
    partial class FacturaModificationA
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atraccion.Microservicios.Factura.DataAccess.Entities.Factura", b =>
                {
                    b.Property<int>("FacId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("fac_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FacId"));

                    b.Property<int>("CliId")
                        .HasColumnType("integer");

                    b.Property<string>("FacEstado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("fac_estado");

                    b.Property<DateTime?>("FacFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fac_fecha_eliminacion");

                    b.Property<DateTime>("FacFechaEmision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fac_fecha_emision");

                    b.Property<DateTime?>("FacFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fac_fecha_mod");

                    b.Property<string>("FacGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fac_guid");

                    b.Property<string>("FacIpEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("fac_ip_eliminacion");

                    b.Property<string>("FacIpIngreso")
                        .HasColumnType("text")
                        .HasColumnName("fac_ip_ingreso");

                    b.Property<string>("FacIpMod")
                        .HasColumnType("text")
                        .HasColumnName("fac_ip_mod");

                    b.Property<string>("FacNumero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fac_numero");

                    b.Property<string>("FacObservacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fac_observacion");

                    b.Property<string>("FacOrigenCanal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fac_origen_canal");

                    b.Property<decimal>("FacTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("fac_total");

                    b.Property<string>("FacUsuarioEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("fac_usuario_eliminacion");

                    b.Property<string>("FacUsuarioIngreso")
                        .HasColumnType("text")
                        .HasColumnName("fac_usuario_ingreso");

                    b.Property<string>("FacUsuarioMod")
                        .HasColumnType("text")
                        .HasColumnName("fac_usuario_mod");

                    b.Property<int>("RevId")
                        .HasColumnType("integer")
                        .HasColumnName("rev_id");

                    b.HasKey("FacId");

                    b.ToTable("FACTURAS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
