// <auto-generated />
using System;
using Atraccion.Microservicios.Cliente.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atraccion.Microservicios.Cliente.DataAccess.Migrations
{
    [DbContext(typeof(AtraccionesDbContext))]
    [Migration("20260513205724_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atraccion.Microservicios.Cliente.DataAccess.Entities.Cliente", b =>
                {
                    b.Property<int>("CliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cli_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CliId"));

                    b.Property<string>("CliApellidos")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cli_apellidos");

                    b.Property<string>("CliCorreo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("cli_correo");

                    b.Property<string>("CliDireccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("cli_direccion");

                    b.Property<string>("CliEstado")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("cli_estado");

                    b.Property<DateTime?>("CliFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cli_fecha_eliminacion");

                    b.Property<DateTime>("CliFechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cli_fecha_ingreso");

                    b.Property<string>("CliGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cli_guid");

                    b.Property<string>("CliIpEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("cli_ip_eliminacion");

                    b.Property<string>("CliIpIngreso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cli_ip_ingreso");

                    b.Property<string>("CliNombres")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cli_nombres");

                    b.Property<string>("CliNumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cli_numero_identificacion");

                    b.Property<string>("CliTelefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cli_telefono");

                    b.Property<string>("CliTipoIdentificacion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cli_tipo_identificacion");

                    b.Property<string>("CliUsuarioEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("cli_usuario_eliminacion");

                    b.Property<string>("CliUsuarioIngreso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cli_usuario_ingreso");

                    b.Property<int?>("UsuId")
                        .HasColumnType("integer")
                        .HasColumnName("usu_id");

                    b.HasKey("CliId");

                    b.ToTable("CLIENTES", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
