// <auto-generated />
using System;
using Atraccion.Microservicios.Reserva.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atraccion.Microservicios.Reserva.DataAccess.Migrations
{
    [DbContext(typeof(AtraccionesDbContext))]
    partial class AtraccionesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atraccion.Microservicios.Reserva.DataAccess.Entities.DetalleReserva", b =>
                {
                    b.Property<int>("RevId")
                        .HasColumnType("integer")
                        .HasColumnName("rev_id");

                    b.Property<int>("TicId")
                        .HasColumnType("integer")
                        .HasColumnName("tck_id");

                    b.Property<string>("DetRevGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rdet_guid");

                    b.Property<int>("TicCantidad")
                        .HasColumnType("integer");

                    b.Property<string>("TicGuid")
                        .HasColumnType("text")
                        .HasColumnName("tck_guid");

                    b.Property<double>("TicPrecioUnitario")
                        .HasColumnType("double precision")
                        .HasColumnName("rdet_precio_unit");

                    b.Property<double>("TicSubtotal")
                        .HasColumnType("double precision")
                        .HasColumnName("rdet_subtotal");

                    b.Property<string>("TicTipoParticipante")
                        .HasColumnType("text")
                        .HasColumnName("rdet_tipo_participante");

                    b.Property<string>("TicTitulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RevId", "TicId");

                    b.ToTable("RESERVA_DETALLE", (string)null);
                });

            modelBuilder.Entity("Atraccion.Microservicios.Reserva.DataAccess.Entities.Reserva", b =>
                {
                    b.Property<int>("RevId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rev_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RevId"));

                    b.Property<string>("AtNombre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("at_nombre");

                    b.Property<int?>("CliId")
                        .HasColumnType("integer")
                        .HasColumnName("cli_id");

                    b.Property<string>("HorFecha")
                        .HasColumnType("text")
                        .HasColumnName("hor_fecha");

                    b.Property<string>("HorGuid")
                        .HasColumnType("text")
                        .HasColumnName("horario_guid");

                    b.Property<string>("HorHoraFin")
                        .HasColumnType("text")
                        .HasColumnName("hor_hora_fin");

                    b.Property<string>("HorHoraInicio")
                        .HasColumnType("text")
                        .HasColumnName("hor_hora_inicio");

                    b.Property<int?>("HorId")
                        .HasColumnType("integer")
                        .HasColumnName("hor_id");

                    b.Property<string>("RevCanal")
                        .HasColumnType("text")
                        .HasColumnName("rev_canal");

                    b.Property<string>("RevCodigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rev_codigo");

                    b.Property<string>("RevEstado")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("rev_estado");

                    b.Property<DateTime?>("RevFechaCancelacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rev_fecha_cancelacion");

                    b.Property<DateTime?>("RevFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rev_fecha_mod");

                    b.Property<DateTime>("RevFechaReservaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rev_fecha_reserva_utc");

                    b.Property<string>("RevGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rev_guid");

                    b.Property<string>("RevIpCancelacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("rev_ip_cancelacion");

                    b.Property<string>("RevIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("rev_ip_ingreso");

                    b.Property<string>("RevIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("rev_ip_mod");

                    b.Property<string>("RevMotivoCancelacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("rev_motivo_cancelacion");

                    b.Property<double>("RevSubtotal")
                        .HasColumnType("double precision")
                        .HasColumnName("rev_subtotal");

                    b.Property<double>("RevTotal")
                        .HasColumnType("double precision")
                        .HasColumnName("rev_total");

                    b.Property<string>("RevUsuarioCancelacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rev_usuario_cancelacion");

                    b.Property<string>("RevUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rev_usuario_ingreso");

                    b.Property<string>("RevUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rev_usuario_mod");

                    b.Property<double>("RevValorIva")
                        .HasColumnType("double precision")
                        .HasColumnName("rev_valor_iva");

                    b.HasKey("RevId");

                    b.ToTable("RESERVAS", (string)null);
                });

            modelBuilder.Entity("Atraccion.Microservicios.Reserva.DataAccess.Entities.DetalleReserva", b =>
                {
                    b.HasOne("Atraccion.Microservicios.Reserva.DataAccess.Entities.Reserva", "Reserva")
                        .WithMany("Detalles")
                        .HasForeignKey("RevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Atraccion.Microservicios.Reserva.DataAccess.Entities.Reserva", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
