// <auto-generated />
using System;
using Atraccion.Microservicios.Auth.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atraccion.Microservicios.Auth.DataAccess.Migrations
{
    [DbContext(typeof(AtraccionesDbContext))]
    partial class AtraccionesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atraccion.Microservicios.Auth.DataAccess.Entities.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolId"));

                    b.Property<string>("RolDescripcion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("rol_descripcion");

                    b.Property<string>("RolEstado")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("rol_estado");

                    b.Property<string>("RolGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol_guid");

                    b.HasKey("RolId");

                    b.ToTable("ROL", (string)null);
                });

            modelBuilder.Entity("Atraccion.Microservicios.Auth.DataAccess.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usu_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuId"));

                    b.Property<string>("UsuEstado")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("usu_estado");

                    b.Property<DateTime?>("UsuFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usu_fecha_eliminacion");

                    b.Property<DateTime?>("UsuFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usu_fecha_mod");

                    b.Property<DateTime>("UsuFechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usu_fecha_registro");

                    b.Property<string>("UsuGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usu_guid");

                    b.Property<string>("UsuIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("usu_ip_eliminacion");

                    b.Property<string>("UsuIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("usu_ip_mod");

                    b.Property<string>("UsuIpRegistro")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("usu_ip_registro");

                    b.Property<string>("UsuLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usu_login");

                    b.Property<string>("UsuPasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("usu_password_hash");

                    b.Property<string>("UsuUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usu_usuario_eliminacion");

                    b.Property<string>("UsuUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usu_usuario_mod");

                    b.Property<string>("UsuUsuarioRegistro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usu_usuario_registro");

                    b.HasKey("UsuId");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("Atraccion.Microservicios.Auth.DataAccess.Entities.UsuarioRol", b =>
                {
                    b.Property<int>("UsuRolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usu_rol_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuRolId"));

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.Property<int>("UsuId")
                        .HasColumnType("integer")
                        .HasColumnName("usu_id");

                    b.HasKey("UsuRolId");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuId");

                    b.ToTable("USUARIOXROL", (string)null);
                });

            modelBuilder.Entity("Atraccion.Microservicios.Auth.DataAccess.Entities.UsuarioRol", b =>
                {
                    b.HasOne("Atraccion.Microservicios.Auth.DataAccess.Entities.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Atraccion.Microservicios.Auth.DataAccess.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Atraccion.Microservicios.Auth.DataAccess.Entities.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Atraccion.Microservicios.Auth.DataAccess.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
