// <auto-generated />
using System;
using Atraccion.Microservicios.Atraccion.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atraccion.Microservicios.Atraccion.DataAccess.Migrations
{
    [DbContext(typeof(AtraccionesDbContext))]
    partial class AtraccionesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Atraccion", b =>
                {
                    b.Property<int>("AtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("at_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AtId"));

                    b.Property<string>("AtDescripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("at_descripcion");

                    b.Property<string>("AtDireccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("at_direccion");

                    b.Property<int?>("AtDuracionMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("at_duracion_minutos");

                    b.Property<string>("AtEstado")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("at_estado");

                    b.Property<DateTime?>("AtFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at_fecha_eliminacion");

                    b.Property<DateTime>("AtFechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at_fecha_ingreso");

                    b.Property<DateTime?>("AtFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at_fecha_mod");

                    b.Property<string>("AtGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("at_guid");

                    b.Property<bool>("AtIncluyeAcompaniante")
                        .HasColumnType("boolean")
                        .HasColumnName("at_incluye_acompaniante");

                    b.Property<bool>("AtIncluyeTransporte")
                        .HasColumnType("boolean")
                        .HasColumnName("at_incluye_transporte");

                    b.Property<string>("AtIpEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("at_ip_eliminacion");

                    b.Property<string>("AtIpIngreso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("at_ip_ingreso");

                    b.Property<string>("AtIpMod")
                        .HasColumnType("text")
                        .HasColumnName("at_ip_mod");

                    b.Property<string>("AtMoneda")
                        .HasColumnType("text");

                    b.Property<string>("AtNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("at_nombre");

                    b.Property<string>("AtNumEstablecimiento")
                        .HasColumnType("text")
                        .HasColumnName("at_num_establecimiento");

                    b.Property<decimal?>("AtPrecioReferencia")
                        .HasColumnType("double(10,2)")
                        .HasColumnName("at_precio_referencia");

                    b.Property<string>("AtPuntoEncuentro")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("at_punto_encuentro");

                    b.Property<string>("AtUsuarioEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("at_usuario_eliminacion");

                    b.Property<string>("AtUsuarioIngreso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("at_usuario_ingreso");

                    b.Property<string>("AtUsuarioMod")
                        .HasColumnType("text")
                        .HasColumnName("at_usuario_mod");

                    b.Property<int>("DesId")
                        .HasColumnType("integer")
                        .HasColumnName("des_id");

                    b.HasKey("AtId");

                    b.HasIndex("DesId");

                    b.ToTable("ATRACCION", (string)null);
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Categoria", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cat_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CatId"));

                    b.Property<string>("CatEstado")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("cat_estado");

                    b.Property<string>("CatGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cat_guid");

                    b.Property<string>("CatNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cat_nombre");

                    b.Property<int?>("CatParentId")
                        .HasColumnType("integer")
                        .HasColumnName("cat_parent_id");

                    b.HasKey("CatId");

                    b.HasIndex("CatParentId");

                    b.ToTable("CATEGORIA", (string)null);
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.CategoriaAtraccion", b =>
                {
                    b.Property<int>("CatId")
                        .HasColumnType("integer")
                        .HasColumnName("cat_id");

                    b.Property<int>("AtId")
                        .HasColumnType("integer")
                        .HasColumnName("at_id");

                    b.HasKey("CatId", "AtId");

                    b.HasIndex("AtId");

                    b.ToTable("CATEGORIA_ATRACCION", (string)null);
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Destino", b =>
                {
                    b.Property<int>("DesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("des_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DesId"));

                    b.Property<string>("DesEstado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("des_estado");

                    b.Property<DateTime?>("DesFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("des_fecha_eliminacion");

                    b.Property<DateTime>("DesFechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("des_fecha_ingreso");

                    b.Property<DateTime?>("DesFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("des_fecha_mod");

                    b.Property<string>("DesGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("des_guid");

                    b.Property<string>("DesImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("des_imagen_url");

                    b.Property<string>("DesIpEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("des_ip_eliminacion");

                    b.Property<string>("DesIpIngreso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("des_ip_ingreso");

                    b.Property<string>("DesIpMod")
                        .HasColumnType("text")
                        .HasColumnName("des_ip_mod");

                    b.Property<string>("DesNombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("des_nombre");

                    b.Property<string>("DesPais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("des_pais");

                    b.Property<string>("DesUsuarioEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("des_usuario_eliminacion");

                    b.Property<string>("DesUsuarioIngreso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("des_usuario_ingreso");

                    b.Property<string>("DesUsuarioMod")
                        .HasColumnType("text")
                        .HasColumnName("des_usuario_mod");

                    b.HasKey("DesId");

                    b.ToTable("DESTINO", (string)null);
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Horario", b =>
                {
                    b.Property<int>("HorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("hor_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HorId"));

                    b.Property<int>("AtId")
                        .HasColumnType("integer")
                        .HasColumnName("at_id");

                    b.Property<int>("HorCuposDisponibles")
                        .HasColumnType("integer")
                        .HasColumnName("hor_cupos_disponibles");

                    b.Property<string>("HorEstado")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("hor_estado");

                    b.Property<DateTime>("HorFecha")
                        .HasColumnType("date")
                        .HasColumnName("hor_fecha");

                    b.Property<DateTime?>("HorFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hor_fecha_eliminacion");

                    b.Property<DateTime>("HorFechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hor_fecha_ingreso");

                    b.Property<DateTime?>("HorFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hor_fecha_mod");

                    b.Property<string>("HorGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hor_guid");

                    b.Property<TimeSpan?>("HorHoraFin")
                        .HasColumnType("time")
                        .HasColumnName("hor_hora_fin");

                    b.Property<TimeSpan>("HorHoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("hor_hora_inicio");

                    b.Property<string>("HorIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("hor_ip_eliminacion");

                    b.Property<string>("HorIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("hor_ip_ingreso");

                    b.Property<string>("HorIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("hor_ip_mod");

                    b.Property<string>("HorUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hor_usuario_eliminacion");

                    b.Property<string>("HorUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hor_usuario_ingreso");

                    b.Property<string>("HorUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hor_usuario_mod");

                    b.HasKey("HorId");

                    b.HasIndex("AtId");

                    b.HasIndex("HorGuid")
                        .IsUnique()
                        .HasDatabaseName("UK_HORARIO_guid");

                    b.ToTable("HORARIO", (string)null);
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Idioma", b =>
                {
                    b.Property<int>("IdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdId"));

                    b.Property<string>("IdEstado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_estado");

                    b.Property<string>("IdNombre")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("id_descripcion");

                    b.HasKey("IdId");

                    b.ToTable("IDIOMA", (string)null);
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.IdiomaAtraccion", b =>
                {
                    b.Property<int>("IdId")
                        .HasColumnType("integer")
                        .HasColumnName("id_id");

                    b.Property<int>("AtId")
                        .HasColumnType("integer")
                        .HasColumnName("at_id");

                    b.Property<int?>("AtraccionAtId")
                        .HasColumnType("integer");

                    b.HasKey("IdId", "AtId");

                    b.HasIndex("AtId");

                    b.HasIndex("AtraccionAtId");

                    b.ToTable("IDIOMA_ATRACCION", (string)null);
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Imagen", b =>
                {
                    b.Property<int>("ImgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("img_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImgId"));

                    b.Property<int>("AtId")
                        .HasColumnType("integer")
                        .HasColumnName("at_id");

                    b.Property<string>("ImgDescripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("img_descripcion");

                    b.Property<string>("ImgEstado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("img_estado");

                    b.Property<DateTime?>("ImgFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("img_fecha_eliminacion");

                    b.Property<DateTime>("ImgFechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("img_fecha_ingreso");

                    b.Property<DateTime?>("ImgFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("img_fecha_mod");

                    b.Property<string>("ImgGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("img_guid");

                    b.Property<string>("ImgIpEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("img_ip_eliminacion");

                    b.Property<string>("ImgIpIngreso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("img_ip_ingreso");

                    b.Property<string>("ImgIpMod")
                        .HasColumnType("text")
                        .HasColumnName("img_ip_mod");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("img_url");

                    b.Property<string>("ImgUsuarioEliminacion")
                        .HasColumnType("text")
                        .HasColumnName("img_usuario_eliminacion");

                    b.Property<string>("ImgUsuarioIngreso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("img_usuario_ingreso");

                    b.Property<string>("ImgUsuarioMod")
                        .HasColumnType("text")
                        .HasColumnName("img_usuario_mod");

                    b.HasKey("ImgId");

                    b.HasIndex("AtId");

                    b.ToTable("IMAGEN", (string)null);
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Incluye", b =>
                {
                    b.Property<int>("IncId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("inc_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IncId"));

                    b.Property<string>("IncDescripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("inc_descripcion");

                    b.Property<string>("IncEstado")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("inc_estado");

                    b.HasKey("IncId");

                    b.ToTable("INCLUYE", (string)null);
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.IncluyeAtraccion", b =>
                {
                    b.Property<int>("IncId")
                        .HasColumnType("integer")
                        .HasColumnName("inc_id");

                    b.Property<int>("AtId")
                        .HasColumnType("integer")
                        .HasColumnName("at_id");

                    b.Property<int?>("AtraccionAtId")
                        .HasColumnType("integer");

                    b.HasKey("IncId", "AtId");

                    b.HasIndex("AtId");

                    b.HasIndex("AtraccionAtId");

                    b.ToTable("ATRACCION_INCLUYE", (string)null);
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.NoIncluye", b =>
                {
                    b.Property<int>("NoIncId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("noinc_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NoIncId"));

                    b.Property<string>("NoIncDescripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("inc_descripcion");

                    b.Property<string>("NoIncEstado")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("inc_estado");

                    b.HasKey("NoIncId");

                    b.ToTable("NOINCLUYE", (string)null);
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.NoIncluyeAtraccion", b =>
                {
                    b.Property<int>("NoIncId")
                        .HasColumnType("integer")
                        .HasColumnName("noinc_id");

                    b.Property<int>("AtId")
                        .HasColumnType("integer")
                        .HasColumnName("at_id");

                    b.Property<int?>("AtraccionAtId")
                        .HasColumnType("integer");

                    b.HasKey("NoIncId", "AtId");

                    b.HasIndex("AtId");

                    b.HasIndex("AtraccionAtId");

                    b.ToTable("ATRACCION_NOINCLUYE", (string)null);
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Resena", b =>
                {
                    b.Property<int>("ResenaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rsn_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResenaId"));

                    b.Property<int>("AtId")
                        .HasColumnType("integer")
                        .HasColumnName("at_id");

                    b.Property<int>("CliId")
                        .HasColumnType("integer")
                        .HasColumnName("cli_id");

                    b.Property<int>("ResenaCalificacion")
                        .HasColumnType("integer")
                        .HasColumnName("rsn_rating");

                    b.Property<string>("ResenaComentario")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rsn_comentario");

                    b.Property<string>("ResenaEstado")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("rsn_estado");

                    b.Property<DateTime>("ResenaFechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rsn_fecha_creacion");

                    b.Property<DateTime?>("ResenaFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rsn_fecha_eliminacion");

                    b.Property<DateTime?>("ResenaFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rsn_fecha_mod");

                    b.Property<string>("ResenaGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rsn_guid");

                    b.Property<string>("ResenaIpCreacion")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("rsn_ip_creacion");

                    b.Property<string>("ResenaIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("rsn_ip_eliminacion");

                    b.Property<string>("ResenaIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("rsn_ip_mod");

                    b.Property<string>("ResenaUsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rsn_usuario_creacion");

                    b.Property<string>("ResenaUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rsn_usuario_eliminacion");

                    b.Property<string>("ResenaUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rsn_usuario_mod");

                    b.Property<int?>("RevId")
                        .HasColumnType("integer")
                        .HasColumnName("rev_id");

                    b.HasKey("ResenaId");

                    b.HasIndex("AtId");

                    b.ToTable("RESENIA", (string)null);
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<string>("TagDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag_description");

                    b.HasKey("TagId");

                    b.ToTable("TAG", (string)null);
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.TagAtraccion", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.Property<int>("AtId")
                        .HasColumnType("integer")
                        .HasColumnName("at_id");

                    b.HasKey("TagId", "AtId");

                    b.HasIndex("AtId");

                    b.ToTable("TAG_ATRACCION", (string)null);
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Ticket", b =>
                {
                    b.Property<int>("TicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tck_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TicId"));

                    b.Property<int>("HorId")
                        .HasColumnType("integer")
                        .HasColumnName("hor_id");

                    b.Property<string>("TicEstado")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("tck_estado");

                    b.Property<DateTime?>("TicFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tck_fecha_eliminacion");

                    b.Property<DateTime>("TicFechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tck_fecha_ingreso");

                    b.Property<DateTime?>("TicFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tck_fecha_mod");

                    b.Property<string>("TicGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tck_guid");

                    b.Property<string>("TicIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("tck_ip_eliminacion");

                    b.Property<string>("TicIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("tck_ip_ingreso");

                    b.Property<string>("TicIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("tck_ip_mod");

                    b.Property<decimal>("TicPrecio")
                        .HasColumnType("numeric")
                        .HasColumnName("tck_precio");

                    b.Property<string>("TicTipoParticipante")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tck_tipo_participante");

                    b.Property<string>("TicTitulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("tck_titulo");

                    b.Property<string>("TicUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tck_usuario_eliminacion");

                    b.Property<string>("TicUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tck_usuario_ingreso");

                    b.Property<string>("TicUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tck_usuario_mod");

                    b.HasKey("TicId");

                    b.HasIndex("HorId");

                    b.ToTable("TICKET", (string)null);
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Atraccion", b =>
                {
                    b.HasOne("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Destino", "Destino")
                        .WithMany("Atracciones")
                        .HasForeignKey("DesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destino");
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Categoria", b =>
                {
                    b.HasOne("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Categoria", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("CatParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.CategoriaAtraccion", b =>
                {
                    b.HasOne("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Atraccion", "Atraccion")
                        .WithMany("CategoriaAtracciones")
                        .HasForeignKey("AtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Categoria", "Categoria")
                        .WithMany("CategoriaAtracciones")
                        .HasForeignKey("CatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Horario", b =>
                {
                    b.HasOne("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Atraccion", "Atraccion")
                        .WithMany("Horario")
                        .HasForeignKey("AtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atraccion");
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.IdiomaAtraccion", b =>
                {
                    b.HasOne("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Atraccion", "Atraccion")
                        .WithMany()
                        .HasForeignKey("AtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Atraccion", null)
                        .WithMany("IdiomaAtracciones")
                        .HasForeignKey("AtraccionAtId");

                    b.HasOne("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Idioma", "Idioma")
                        .WithMany("IdiomaAtracciones")
                        .HasForeignKey("IdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");

                    b.Navigation("Idioma");
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Imagen", b =>
                {
                    b.HasOne("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Atraccion", "Atraccion")
                        .WithMany("Imagenes")
                        .HasForeignKey("AtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.IncluyeAtraccion", b =>
                {
                    b.HasOne("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Atraccion", "Atraccion")
                        .WithMany()
                        .HasForeignKey("AtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Atraccion", null)
                        .WithMany("IncluyeAtracciones")
                        .HasForeignKey("AtraccionAtId");

                    b.HasOne("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Incluye", "Incluye")
                        .WithMany("IncluyeAtracciones")
                        .HasForeignKey("IncId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atraccion");

                    b.Navigation("Incluye");
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.NoIncluyeAtraccion", b =>
                {
                    b.HasOne("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Atraccion", "Atraccion")
                        .WithMany()
                        .HasForeignKey("AtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Atraccion", null)
                        .WithMany("NoIncluyeAtracciones")
                        .HasForeignKey("AtraccionAtId");

                    b.HasOne("Atraccion.Microservicios.Atraccion.DataAccess.Entities.NoIncluye", "NoIncluye")
                        .WithMany("NoIncluyeAtracciones")
                        .HasForeignKey("NoIncId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atraccion");

                    b.Navigation("NoIncluye");
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Resena", b =>
                {
                    b.HasOne("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Atraccion", "Atraccion")
                        .WithMany("Resena")
                        .HasForeignKey("AtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atraccion");
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.TagAtraccion", b =>
                {
                    b.HasOne("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Atraccion", "Atraccion")
                        .WithMany("TagAtracciones")
                        .HasForeignKey("AtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Tag", "Tag")
                        .WithMany("TagAtracciones")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Ticket", b =>
                {
                    b.HasOne("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Horario", "Horario")
                        .WithMany("Ticket")
                        .HasForeignKey("HorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Horario");
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Atraccion", b =>
                {
                    b.Navigation("CategoriaAtracciones");

                    b.Navigation("Horario");

                    b.Navigation("IdiomaAtracciones");

                    b.Navigation("Imagenes");

                    b.Navigation("IncluyeAtracciones");

                    b.Navigation("NoIncluyeAtracciones");

                    b.Navigation("Resena");

                    b.Navigation("TagAtracciones");
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Categoria", b =>
                {
                    b.Navigation("CategoriaAtracciones");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Destino", b =>
                {
                    b.Navigation("Atracciones");
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Horario", b =>
                {
                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Idioma", b =>
                {
                    b.Navigation("IdiomaAtracciones");
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Incluye", b =>
                {
                    b.Navigation("IncluyeAtracciones");
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.NoIncluye", b =>
                {
                    b.Navigation("NoIncluyeAtracciones");
                });

            modelBuilder.Entity("Atraccion.Microservicios.Atraccion.DataAccess.Entities.Tag", b =>
                {
                    b.Navigation("TagAtracciones");
                });
#pragma warning restore 612, 618
        }
    }
}
